[tool.poetry]
name = "aoc"
version = "0.1.0"
description = "Advent of Code project"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
jupyter = {extras = ["notebook"], version = "^1.0.0"}
arrow = "^0.17.0"
multiprocess = "^0.70.11"
advent-of-code-data = {path = "../../contrib/advent-of-code-data", develop = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
